In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [58]:
arr1 = np.array([[5, 2], [3, 4]])
arr1

array([[5, 2],
       [3, 4]])

In [4]:
def Transpose(matrix):
    return matrix.transpose()

In [9]:
def Sum(matrix):
    return matrix.sum()

In [21]:
def Linalg(matrix):
    return np.linalg.det(matrix)

In [63]:
print(Transpose(arr1))
print(Odw(arr1))
print(np.sort(arr1))
print(arr1.cumsum())
print(arr1.diagonal())
print(np.nonzero(arr1))
print(arr1.squeeze())
print(2*arr1)
arr1.ravel()

[[5 3]
 [2 4]]
[[ 0.28571429 -0.14285714]
 [-0.21428571  0.35714286]]
[[2 5]
 [3 4]]
[ 5  7 10 14]
[5 4]
(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))
[[5 2]
 [3 4]]
[[10  4]
 [ 6  8]]


array([5, 2, 3, 4])

In [24]:
def Slad(matrix):
    return np.trace(matrix)

In [25]:
def Odw(matrix):
    return np.linalg.inv(matrix)

In [61]:
def Pomno(matrix, liczb):
    return liczb*matrix

In [62]:
print(Pomno(arr1, 3))

[[15  6]
 [ 9 12]]
